# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Sushrut Bidwai
description: "Personal website of Sushrut Bidwai"
keywords: "sushrut bidwai"
url: http://sushrutbidwai.com
baseurl: ""
# baseurl: ""

google_analytics: UA-7224484-2
repo: http://github.com/sushrutb/sushrutb.github.io
disqus_shortname: "sushrutbidwai"
disqus_site_shortname: "sushrutbidwaicom"

# Author settings
author:
  name      : Sushrut Bidwai
  job       : Programmer
  bio       : "Programmer and entrepreneur."
  thumb     : /images/author.jpg
  email     : sb@sushrutbidwai.com
  url       : http://sushrutbidwai.com
  github    : http://github.com/sushrutb
  twitter   : http://twitter.com/IamSB
  facebook  : http://facebook.com/sushrut.bidwai
  linkedin  : https://au.linkedin.com/in/sushrutbidwai

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
